openapi: 3.0.3

info:
  title: My Api
  description: My Api
  version: 1.0.0
  contact: {}

servers:
  - url: http://localhost:3000

tags:
  - name: rules

components:
  examples:
    requestExample:
      $ref: ./requestExample.yml
    responseExample:
      $ref: ./responseExample.yml
  schemas:
    Rule:
      type: object
      properties:
        rules:
          type: object
          properties:
            name:
              type: string
  parameters:
    RuleId:
      name: id
      description: The ID of the resource.
      in: path
      required: true
      schema:
        type: string

paths:
  /rule/{id}:
    get:
      tags:
        - rules
      description: Get Rule
      operationId: getRule
      parameters:
        - $ref: '#/components/parameters/RuleId'
      responses:
        "200":
          description: Returns a rule
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
              examples:
                responseExample:
                  $ref: "./responseExample"
    put:
      tags:
        - rules
      description: Update Rule
      operationId: updateRule
      parameters:
        - $ref: '#/components/parameters/RuleId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                rule:
                  $ref: "#/components/schemas/Rule"
              required:
                - rule
            examples:
              requestExample:
                $ref: "#/components/examples/requestExample"

      responses:
        "200":
          description: Returns a rule
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rule"
              examples:
                responseExample:
                  $ref: "#/components/examples/responseExample"
